# Openshift-logging 5,8 elasticsearch

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging #{{ openshiftLoggingNamespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-logging
  namespace: openshift-logging #{{ openshiftLoggingNamespace }}
spec:
#  targetNamespaces: 
#  - openshift-logging #{{ openshiftLoggingNamespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging #{{ openshiftLoggingNamespace }}
spec:
  channel: stable-5.8 #"{{ openshiftVersion }}"
  installPlanApproval: Automatic #"{{ modeInstallPlan }}"
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat #{{ openshiftOperatorRedHatNamespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true" 
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat #{{ openshiftOperatorRedHatNamespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators-redhat #{{ openshiftOperatorRedHatNamespace }}
spec:
  channel: stable-5.8 #"{{ openshiftVersion }}"
  installPlanApproval: Automatic #"{{ modeInstallPlan }}"
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: elasticsearch-operator
---

apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging #{{ k8sNamespace }}
spec:
  managementState: Managed
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 3 #{{ elasticNodeCount }}
      # nodeSelector:
      #   {{ nodeSelector }}
      redundancyPolicy: ZeroRedundancy #{{ elasticRedundancyPolicy }}
      storage:
        storageClassName: ocs-external-storagecluster-ceph-rbd #"{{ elasticStorageClass }}"
        size: 10G #{{ elasticStorageSize }}
      resources:
        limits:
          cpu: 2 #{{ elasticCPULimit }}
          memory: 4Gi #{{ elasticMemoryLimit }}
        requests:
          cpu: 300m #{{ elasticCPURequest }}
          memory: 1G #{{ elasticMemoryRequest }}
    retentionPolicy: 
      application:
        maxAge: 5d #{{ maxApplicationRetention }}
      infra:
        maxAge: 7d #{{ maxInfraRetention }}
      audit:
        maxAge: 7d #{{ maxAuditRetention }}
  visualization:
    type: kibana
    kibana:
      replicas: 1
      # nodeSelector:
      #   {{ nodeSelector }}
      resources:
        limits:
          cpu: 1 #{{ kibanaCPULimit }}
          memory: 1Gi #{{ kibanaMemoryLimit }}
        requests:
          cpu: 500m #{{ kibanaCPURequest }}
          memory: 500Mi #{{ kibanaMemoryRequest }}   
  collection:
    logs:
      type: fluentd
      fluentd:
        resources:
          limits:
            cpu: 500m #{{ fluentdCPULimit }}
            memory: 1Gi #{{ fluentdMemoryLimit }}
          requests: 
            cpu: 200m #{{ fluentdCPURequest }}
            memory: 1Gi #{{ fluentdMemoryRequest }} 



#If need audit logs, Forwarder needs to be implemented. 

---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  pipelines: 
  - name: all-to-default
    inputRefs:
    - infrastructure
    - application
    - audit
    outputRefs:
    - default