---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging #{{ openshiftLoggingNamespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-logging
  namespace: openshift-logging #{{ openshiftLoggingNamespace }}
spec:
#  targetNamespaces: 
#  - openshift-logging #{{ openshiftLoggingNamespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging #{{ openshiftLoggingNamespace }}
spec:
  channel: stable-6.0 #"{{ openshiftVersion }}"
  installPlanApproval: Automatic #"{{ modeInstallPlan }}"
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---


apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat #{{ openshiftOperatorRedHatNamespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true" 
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat #{{ openshiftOperatorRedHatNamespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: openshift-operators-redhat #{{ openshiftOperatorRedHatNamespace }}
spec:
  channel: stable-6.0 #"{{ openshiftVersion }}"
  installPlanApproval: Automatic #"{{ modeInstallPlan }}"
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: loki-operator


---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-observability-operator #{{ observabilityOperatorNamespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-cluster-observability-operator #{{ observabilityOperatorNamespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-cluster-observability-operator #{{ observabilityOperatorNamespace }}
spec:
  channel: stable #"{{ openshiftVersion }}"
  installPlanApproval: Automatic #"{{ modeInstallPlan }}"
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: cluster-observability-operator
---